apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdF9wYXNzd29yZA==
  mysql-db: c3ByaW5nZGI=
  mysql-user: c3ByaW5ndXNlcg==
  mysql-password: c3ByaW5nX3Bhc3N3b3Jk